import Head from "next/head";
import { useEffect, useMemo, useState } from "react";

const GREEN = "#00A859";
const GOLD = "#FFCB05";
const BG = "#FCFCFD";
const BG_ALT = "#F7F8F9";
const TEXT = "#171717";
const SUB = "#626262";
const DIM = "#969696";
const BORDER = "#E8E8E8";
const SERIF = "'Source Serif 4', Georgia, serif";
const SANS = "'Inter', -apple-system, sans-serif";
const FONSECA_IMG = "https://www.atptour.com/-/media/alias/player-headshot/f0fv";
const PLAYER_IMG = { Zverev: "https://www.atptour.com/-/media/alias/player-headshot/z355", Berrettini: "https://www.atptour.com/-/media/alias/player-headshot/bk40", Nakashima: "https://www.atptour.com/-/media/alias/player-headshot/n0ae", Rinderknech: "https://www.atptour.com/-/media/alias/player-headshot/rc91", Diallo: "https://www.atptour.com/-/media/alias/player-headshot/d0f6", Bublik: "https://www.atptour.com/-/media/alias/player-headshot/b0bk", Cerundolo: "https://www.atptour.com/-/media/alias/player-headshot/c0aq", Davidovich: "https://www.atptour.com/-/media/alias/player-headshot/d0au" };
const COUNTRY_FLAGS = { Brazil: "🇧🇷", Brasil: "🇧🇷", Italy: "🇮🇹", Itália: "🇮🇹", USA: "🇺🇸", "United States": "🇺🇸", Canada: "🇨🇦", France: "🇫🇷", Argentina: "🇦🇷", Monaco: "🇲🇨", Mônaco: "🇲🇨", Germany: "🇩🇪", Alemanha: "🇩🇪" };

function formatTimeAgo(d){ if(!d) return ""; try{ const m=Math.floor((Date.now()-new Date(d).getTime())/60000); if(m<1) return "agora"; if(m<60) return `há ${m} min`; const h=Math.floor(m/60); if(h<24) return `há ${h}h`; const dd=Math.floor(h/24); return dd===1?"ontem":`há ${dd} dias`; }catch{return "";} }
function formatDateLabel(date){ if(!date) return "A definir"; try{ return new Date(date).toLocaleDateString("pt-BR",{ weekday:"long", day:"numeric", month:"long", timeZone:"America/Sao_Paulo" }).replace(/^./,c=>c.toUpperCase()); }catch{return "A definir";} }
function formatTimeLabel(date){ if(!date) return "A definir"; try{ return new Date(date).toLocaleTimeString("pt-BR",{ hour:"2-digit", minute:"2-digit", timeZone:"America/Sao_Paulo" }); }catch{return "A definir";} }
function buildCountdownLabel(date){ if(!date) return ""; const diff=new Date(date).getTime()-Date.now(); if(diff<=0) return "Ao vivo ou já começou"; const days=Math.floor(diff/86400000); const hours=Math.floor((diff%86400000)/3600000); const minutes=Math.floor((diff%3600000)/60000); const parts=[]; if(days>0) parts.push(`${days} ${days===1?"dia":"dias"}`); if(hours>0) parts.push(`${hours} ${hours===1?"hora":"horas"}`); if(minutes>0&&days===0) parts.push(`${minutes} ${minutes===1?"minuto":"minutos"}`); return parts.length?parts.join(" e "):"Menos de 1 minuto"; }
function pickOpponentImage(name){ if(!name) return null; const found=Object.keys(PLAYER_IMG).find(k=>name.includes(k)); return found?PLAYER_IMG[found]:null; }
function SectionLabel({children}){ return <p style={{margin:"0 0 12px",fontSize:11,fontWeight:800,color:DIM,fontFamily:SANS,textTransform:"uppercase",letterSpacing:"0.08em"}}>{children}</p>; }
function SoftCard({children,padding=20}){ return <div style={{background:"#fff",borderRadius:22,border:`1px solid ${BORDER}`,padding,boxShadow:"0 10px 30px rgba(15,23,42,0.05)"}}>{children}</div>; }
function StatPill({label,value,accent=TEXT}){ return <div style={{textAlign:"center",background:BG_ALT,border:`1px solid ${BORDER}`,borderRadius:14,padding:"14px 10px"}}><span style={{display:"block",fontSize:18,fontWeight:800,color:accent,fontFamily:SANS,lineHeight:1}}>{value}</span><span style={{display:"block",fontSize:9,fontWeight:700,color:DIM,fontFamily:SANS,marginTop:4,textTransform:"uppercase",letterSpacing:"0.05em"}}>{label}</span></div>; }
function NewsItem({item,noBorder=false}){ return <article style={{padding:"18px 0",borderBottom:noBorder?"none":`1px solid ${BORDER}`}}><div style={{display:"flex",alignItems:"center",gap:8,marginBottom:8}}><span style={{fontSize:11,fontWeight:700,color:GREEN,fontFamily:SANS}}>{item.category||"Notícia"}</span><span style={{fontSize:11,color:DIM,fontFamily:SANS}}>{item.source||"Fonte"}</span><span style={{fontSize:11,color:DIM,fontFamily:SANS,marginLeft:"auto"}}>{formatTimeAgo(item.date)}</span></div><h3 style={{margin:"0 0 6px",fontSize:18,fontWeight:700,color:TEXT,fontFamily:SERIF,lineHeight:1.35}}>{item.title}</h3>{item.summary?<p style={{margin:0,fontSize:14,color:SUB,fontFamily:SANS,lineHeight:1.6}}>{item.summary}</p>:null}</article>; }

function MatchInfoRow({leftLabel,leftValue,rightLabel,rightValue}){
  return <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10}}><div style={{background:"rgba(255,255,255,0.06)",border:"1px solid rgba(255,255,255,0.08)",borderRadius:16,padding:"14px 16px"}}><div style={{fontSize:10,fontWeight:700,color:"rgba(255,255,255,0.34)",fontFamily:SANS,textTransform:"uppercase",letterSpacing:"0.06em",marginBottom:4}}>{leftLabel}</div><div style={{fontSize:15,fontWeight:800,color:"#fff",fontFamily:SANS,lineHeight:1.2}}>{leftValue}</div></div><div style={{background:"rgba(255,255,255,0.06)",border:"1px solid rgba(255,255,255,0.08)",borderRadius:16,padding:"14px 16px"}}><div style={{fontSize:10,fontWeight:700,color:"rgba(255,255,255,0.34)",fontFamily:SANS,textTransform:"uppercase",letterSpacing:"0.06em",marginBottom:4}}>{rightLabel}</div><div style={{fontSize:15,fontWeight:800,color:"#fff",fontFamily:SANS,lineHeight:1.2}}>{rightValue}</div></div></div>;
}

function HeroCard({ duelData }){
  const f=duelData.probability?.fonseca ?? null;
  const o=duelData.probability?.opponent ?? null;
  return <section style={{background:"linear-gradient(160deg, #081222 0%, #0b1d39 55%, #0b1628 100%)",borderRadius:28,overflow:"hidden",boxShadow:"0 18px 40px rgba(8,12,20,0.18)"}}>
    <div style={{padding:"18px 18px 12px",borderBottom:"1px solid rgba(255,255,255,0.06)"}}>
      <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:10,marginBottom:10,flexWrap:"wrap"}}>
        <div style={{display:"flex",alignItems:"center",gap:8,flexWrap:"wrap"}}>
          <span style={{fontSize:11,fontWeight:800,color:"#4FC3F7",fontFamily:SANS,textTransform:"uppercase",letterSpacing:"0.08em"}}>Próximo jogo</span>
          <span style={{fontSize:11,color:"rgba(255,255,255,0.40)",fontFamily:SANS}}>{duelData.round}</span>
        </div>
        <span style={{fontSize:10,fontWeight:800,color:"#F59E0B",background:"rgba(245,158,11,0.12)",padding:"6px 12px",borderRadius:999,fontFamily:SANS,textTransform:"uppercase",letterSpacing:"0.08em"}}>{duelData.surface}</span>
      </div>
      <h1 style={{margin:0,fontSize:18,fontWeight:700,color:"rgba(255,255,255,0.78)",fontFamily:SANS,lineHeight:1.2}}>{duelData.tournamentCategory}</h1>
      <div style={{fontSize:42,fontWeight:800,color:"#fff",fontFamily:SERIF,letterSpacing:"-0.03em",lineHeight:1.05,marginTop:4}}>{duelData.tournamentName}</div>
    </div>

    <div style={{padding:"18px"}}>
      <div style={{background:"linear-gradient(180deg, rgba(255,255,255,0.05), rgba(255,255,255,0.03))",border:"1px solid rgba(255,255,255,0.07)",borderRadius:24,padding:"18px 14px 16px",marginBottom:14}}>
        <div style={{display:"grid",gridTemplateColumns:"1fr auto 1fr",alignItems:"center",gap:6}}>
          <div style={{textAlign:"center"}}><div style={{width:94,height:94,borderRadius:"50%",overflow:"hidden",margin:"0 auto 10px",border:`3px solid ${GREEN}55`,boxShadow:"0 0 0 6px rgba(0,168,89,0.08)"}}><img src={duelData.joao.image} alt={duelData.joao.name} style={{width:"100%",height:"100%",objectFit:"cover"}}/></div><div style={{fontSize:16,fontWeight:800,color:"#fff",fontFamily:SERIF}}>{duelData.joao.name}</div><div style={{fontSize:12,color:"rgba(255,255,255,0.55)",fontFamily:SANS,marginTop:4}}>{duelData.joao.flag} #{duelData.joao.ranking}</div></div>
          <div style={{textAlign:"center",padding:"0 8px"}}><div style={{fontSize:22,fontWeight:800,color:"rgba(255,255,255,0.18)",fontFamily:SANS}}>VS</div></div>
          <div style={{textAlign:"center"}}><div style={{width:94,height:94,borderRadius:"50%",overflow:"hidden",margin:"0 auto 10px",border:"3px solid rgba(255,255,255,0.16)",boxShadow:"0 0 0 6px rgba(255,255,255,0.05)"}}>{duelData.opponent.image ? <img src={duelData.opponent.image} alt={duelData.opponent.name} style={{width:"100%",height:"100%",objectFit:"cover"}}/> : <div style={{width:"100%",height:"100%",display:"flex",alignItems:"center",justifyContent:"center",background:"rgba(255,255,255,0.08)",color:"rgba(255,255,255,0.5)",fontSize:28,fontWeight:800,fontFamily:SANS}}>{duelData.opponent.name?.[0] || "?"}</div>}</div><div style={{fontSize:16,fontWeight:800,color:"#fff",fontFamily:SERIF}}>{duelData.opponent.name}</div><div style={{fontSize:12,color:"rgba(255,255,255,0.55)",fontFamily:SANS,marginTop:4}}>{duelData.opponent.flag} {duelData.opponent.ranking ? `#${duelData.opponent.ranking}` : ""}</div></div>
        </div>
      </div>

      <div style={{display:"grid",gap:10,marginBottom:12}}>
        <MatchInfoRow leftLabel="Data" leftValue={duelData.dateLabel} rightLabel="Horário em Brasília" rightValue={duelData.timeLabel} />
        <MatchInfoRow leftLabel="Quadra" leftValue={duelData.courtLabel} rightLabel="Onde assistir" rightValue={duelData.broadcastLabel} />
      </div>

      <div style={{background:"linear-gradient(180deg, rgba(79,195,247,0.12), rgba(79,195,247,0.08))",border:"1px solid rgba(79,195,247,0.18)",borderRadius:18,padding:"14px 16px",textAlign:"center",marginBottom:12}}><div style={{fontSize:11,fontWeight:800,color:"#4FC3F7",fontFamily:SANS,textTransform:"uppercase",letterSpacing:"0.08em",marginBottom:4}}>Falta para o jogo</div><div style={{fontSize:18,fontWeight:900,color:"#fff",fontFamily:SANS,lineHeight:1.15}}>{duelData.countdownLabel}</div></div>

      <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10,marginBottom:16}}><a href="https://www.disneyplus.com" target="_blank" rel="noopener noreferrer" style={{background:"linear-gradient(135deg,#F59E0B 0%, #EA8A00 100%)",borderRadius:16,padding:"16px 12px",textAlign:"center",fontSize:14,fontWeight:800,color:"#fff",fontFamily:SANS,textDecoration:"none"}}>Onde assistir</a><button type="button" style={{background:"rgba(255,255,255,0.06)",border:"1px solid rgba(255,255,255,0.10)",borderRadius:16,padding:"16px 12px",textAlign:"center",fontSize:14,fontWeight:800,color:"rgba(255,255,255,0.88)",fontFamily:SANS"}}>Adicionar ao calendário</button></div>

      {f!==null&&o!==null ? <div style={{background:"rgba(255,255,255,0.03)",border:"1px solid rgba(255,255,255,0.06)",borderRadius:18,padding:"14px 14px 12px",marginBottom:14}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"end",marginBottom:8}}><div><div style={{fontSize:11,fontWeight:800,color:"rgba(255,255,255,0.40)",fontFamily:SANS,textTransform:"uppercase",letterSpacing:"0.08em",marginBottom:3}}>João</div><div style={{fontSize:32,fontWeight:900,color:f>=o?"#ffffff":"rgba(255,255,255,0.72)",fontFamily:SANS,lineHeight:1}}>{f}%</div></div><div style={{textAlign:"center",padding:"0 12px"}}><div style={{fontSize:11,fontWeight:800,color:"rgba(255,255,255,0.42)",fontFamily:SANS,textTransform:"uppercase",letterSpacing:"0.08em"}}>Probabilidade de vitória</div></div><div style={{textAlign:"right"}}><div style={{fontSize:11,fontWeight:800,color:"rgba(255,255,255,0.40)",fontFamily:SANS,textTransform:"uppercase",letterSpacing:"0.08em",marginBottom:3}}>{duelData.opponent.name.split(' ').pop()}</div><div style={{fontSize:32,fontWeight:900,color:o>f?"#FF6B6B":"rgba(255,255,255,0.72)",fontFamily:SANS,lineHeight:1}}>{o}%</div></div></div><div style={{height:10,borderRadius:999,overflow:"hidden",display:"flex",background:"rgba(255,255,255,0.05)"}}><div style={{width:`${f}%`,background:"linear-gradient(90deg, #22C55E, #00A859)"}}/><div style={{width:`${o}%`,background:"linear-gradient(90deg, #FF5A5F, #FF7A7E)"}}/></div></div> : null}

      {duelData.factLabel ? <div style={{paddingTop:2,textAlign:"center"}}><div style={{fontSize:11,fontWeight:800,color:"rgba(255,255,255,0.30)",fontFamily:SANS,textTransform:"uppercase",letterSpacing:"0.08em",marginBottom:6}}>Contexto do jogo</div><div style={{fontSize:15,color:"#5CC8FF",fontFamily:SANS,lineHeight:1.45}}>{duelData.factLabel}</div></div> : null}
    </div>
  </section>;
}

function LastMatchCard({ lastMatch, form }){
  const won=lastMatch?.result==="V";
  return <SoftCard padding={22}><div style={{display:"flex",justifyContent:"space-between",alignItems:"start",gap:12,marginBottom:16}}><div><div style={{fontSize:11,fontWeight:800,color:DIM,fontFamily:SANS,textTransform:"uppercase",letterSpacing:"0.08em",marginBottom:8}}>Última partida</div><div style={{fontSize:30,fontWeight:800,color:TEXT,fontFamily:SERIF,lineHeight:1.05}}>{lastMatch?.score || "—"}</div><div style={{fontSize:14,color:SUB,fontFamily:SANS,marginTop:8}}>{lastMatch?.tournament_name || "Último torneio"}{lastMatch?.round ? ` · ${lastMatch.round}` : ""}</div></div><div style={{padding:"8px 12px",borderRadius:999,background: won ? `${GREEN}12` : "#FEE2E2",color: won ? GREEN : "#DC2626",fontSize:12,fontWeight:800,fontFamily:SANS}}>{won?"Vitória":"Derrota"}</div></div><div style={{display:"grid",gridTemplateColumns:"1.2fr .8fr",gap:12}}><div style={{background:BG_ALT,border:`1px solid ${BORDER}`,borderRadius:18,padding:16}}><div style={{fontSize:10,color:DIM,fontFamily:SANS,textTransform:"uppercase",letterSpacing:"0.05em",marginBottom:8}}>Adversário</div><div style={{fontSize:24,fontWeight:800,color:TEXT,fontFamily:SERIF,lineHeight:1.1}}>{lastMatch?.opponent_name || "A definir"}</div><p style={{margin:"12px 0 0",fontSize:14,color:SUB,fontFamily:SANS,lineHeight:1.55}}>{won ? "João venceu" : "João foi superado por"} <strong>{lastMatch?.opponent_name || "o adversário"}</strong>{lastMatch?.score ? ` por ${lastMatch.score}` : ""}{lastMatch?.round ? `, em ${lastMatch.round.toLowerCase()}` : ""}.</p></div><div style={{background:BG_ALT,border:`1px solid ${BORDER}`,borderRadius:18,padding:16}}><div style={{fontSize:10,color:DIM,fontFamily:SANS,textTransform:"uppercase",letterSpacing:"0.05em",marginBottom:8}}>Forma recente</div><div style={{display:"flex",gap:6,flexWrap:"wrap"}}>{form.length?form.map((m,i)=><span key={i} style={{width:28,height:28,borderRadius:8,display:"flex",alignItems:"center",justifyContent:"center",background:m.result==="V"?`${GREEN}14`:"#FEE2E2",color:m.result==="V"?GREEN:"#DC2626",fontSize:11,fontWeight:800,fontFamily:SANS}}>{m.result}</span>):null}</div></div></div></SoftCard>;
}

export default function HomePreviewLiveV7Bold(){
  const [news,setNews]=useState([]); const [nextMatch,setNextMatch]=useState(null); const [lastMatch,setLastMatch]=useState(null); const [player,setPlayer]=useState(null); const [season,setSeason]=useState(null); const [recentForm,setRecentForm]=useState([]); const [prizeMoney,setPrizeMoney]=useState(null); const [tournamentFacts,setTournamentFacts]=useState(null); const [winProb,setWinProb]=useState(null);
  useEffect(()=>{ fetch("/api/news").then(r=>r.json()).then(d=>{ if(d?.news) setNews(d.news); if(d?.nextMatch) setNextMatch(d.nextMatch); if(d?.lastMatch) setLastMatch(d.lastMatch); if(d?.player) setPlayer(d.player); if(d?.season) setSeason(d.season); }).catch(()=>{}); fetch("/api/sofascore-data").then(r=>r.json()).then(d=>{ if(d?.recentForm) setRecentForm(d.recentForm); if(d?.prizeMoney) setPrizeMoney(d.prizeMoney); if(d?.tournamentFacts) setTournamentFacts(d.tournamentFacts); if(d?.winProb) setWinProb(d.winProb); if(d?.season) setSeason(d.season); if(d?.ranking?.ranking) setPlayer(prev=>prev?{...prev,ranking:d.ranking.ranking}:{ranking:d.ranking.ranking}); if(d?.lastMatch?.result) setLastMatch(d.lastMatch); if(d?.nextMatch?.date) setNextMatch(d.nextMatch); }).catch(()=>{}); },[]);

  const duelData = useMemo(()=>{ const opponentName=nextMatch?.opponent_name||"A definir"; const opponentCountry=nextMatch?.opponent_country||""; return { tournamentName:(nextMatch?.tournament_name||"Próxima partida").split(",")[0], tournamentCategory:nextMatch?.tournament_category||"ATP Tour", round:nextMatch?.round||"Rodada a definir", surface:nextMatch?.surface||"A definir", dateLabel:formatDateLabel(nextMatch?.date), timeLabel:formatTimeLabel(nextMatch?.date), courtLabel:nextMatch?.court||"A definir", broadcastLabel:"ESPN 2 · Disney+", countdownLabel:buildCountdownLabel(nextMatch?.date), joao:{name:"J. Fonseca",flag:"🇧🇷",ranking:player?.ranking||40,image:FONSECA_IMG}, opponent:{name:opponentName,flag:COUNTRY_FLAGS[opponentCountry]||"",ranking:nextMatch?.opponent_ranking||null,image:pickOpponentImage(opponentName)}, probability:winProb?{fonseca:Math.round(winProb.fonseca||0),opponent:Math.round(winProb.opponent||0)}:null, factLabel:tournamentFacts?.facts?.[0]?.text||null }; },[nextMatch,player,tournamentFacts,winProb]);

  const form = Array.isArray(recentForm)?recentForm.slice(-5).reverse():[]; const displayNews=news.slice(0,3); const seasonValue=season?.wins!==undefined&&season?.losses!==undefined?`${season.wins}-${season.losses}`:"14-8"; const prizeValue=prizeMoney?(prizeMoney>=1000000?`$${(Math.floor(prizeMoney/100000)/10).toFixed(1)}M`:`$${Math.round(prizeMoney/1000)}K`):"$2.9M";

  return <div style={{minHeight:"100vh",background:BG}}><Head><title>Fonseca News</title><meta name="description" content="Homepage v7 com mudança visual forte no hero" /></Head><style>{"@import url('https://fonts.googleapis.com/css2?family=Source+Serif+4:wght@400;600;700;800&family=Inter:wght@400;500;600;700;800&display=swap');"+"*{box-sizing:border-box;margin:0;padding:0}"+"body{background:#FCFCFD;-webkit-font-smoothing:antialiased}"}</style>
    <header style={{position:"sticky",top:0,zIndex:100,background:"rgba(252,252,253,0.94)",backdropFilter:"blur(20px)",WebkitBackdropFilter:"blur(20px)",borderBottom:`1px solid ${BORDER}`}}><div style={{maxWidth:760,margin:"0 auto",padding:"12px 16px",display:"flex",alignItems:"center",justifyContent:"space-between",gap:10}}><div style={{display:"flex",alignItems:"center",gap:12}}><div style={{width:42,height:42,borderRadius:12,background:"linear-gradient(135deg, #0D1726, #132440)",display:"flex",alignItems:"center",justifyContent:"center",flexShrink:0}}><span style={{fontFamily:SERIF,fontSize:17,fontWeight:800,letterSpacing:"-0.04em"}}><span style={{color:GREEN}}>F</span><span style={{color:GOLD}}>N</span></span></div><div><span style={{fontFamily:SERIF,fontSize:22,fontWeight:800,letterSpacing:"-0.02em"}}><span style={{color:GREEN}}>Fonseca</span> <span style={{color:GOLD}}>News</span></span><span style={{display:"block",fontSize:11,color:DIM,fontFamily:SANS,marginTop:1}}>Tudo sobre João Fonseca, em leitura rápida</span></div></div></div></header>
    <main style={{maxWidth:760,margin:"0 auto",padding:"12px 12px 32px"}}>
      <section style={{paddingBottom:24}}><HeroCard duelData={duelData} /></section>
      <section style={{paddingBottom:24}}><SectionLabel>O que acabou de acontecer</SectionLabel><LastMatchCard lastMatch={lastMatch} form={form} /></section>
      <section style={{paddingBottom:24}}><SectionLabel>O que mudou hoje</SectionLabel><SoftCard padding={22}><div style={{display:"grid",gridTemplateColumns:"repeat(4, 1fr)",gap:10,marginBottom:18}}><StatPill label="Ranking" value={`#${player?.ranking||40}`} accent={GREEN} /><StatPill label="Temporada" value={seasonValue} /><StatPill label="vs Top 10" value="1-4" /><StatPill label="Prize Money" value={prizeValue} accent={GREEN} /></div>{displayNews.length?displayNews.map((item,idx)=><NewsItem key={`${item.title}-${idx}`} item={item} noBorder={idx===displayNews.length-1} />):<div style={{fontSize:14,color:SUB,fontFamily:SANS}}>Carregando notícias...</div>}</SoftCard></section>
    </main></div>;
}

export async function getServerSideProps(){ return { props:{} }; }
